-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.produto
(
    idproduto serial NOT NULL,
    nomeproduto character varying(100) COLLATE pg_catalog."default" NOT NULL,
    precounitario numeric(10, 2) NOT NULL,
    descricao text COLLATE pg_catalog."default",
    idcategoria integer,
    imagem character varying(300) COLLATE pg_catalog."default",
    CONSTRAINT produto_pkey PRIMARY KEY (idproduto)
);

CREATE TABLE IF NOT EXISTS public.categoria
(
    idcategoria serial NOT NULL,
    nomecategoria character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descricao text COLLATE pg_catalog."default",
    CONSTRAINT categoria_pkey PRIMARY KEY (idcategoria)
);

CREATE TABLE IF NOT EXISTS public.pedidoproduto
(
    idpedido integer NOT NULL,
    idproduto integer NOT NULL,
    quantidade integer NOT NULL,
    precounitario numeric(10, 2) NOT NULL,
    CONSTRAINT pedidoproduto_pkey PRIMARY KEY (idpedido, idproduto)
);

CREATE TABLE IF NOT EXISTS public.pedido
(
    idpedido serial NOT NULL,
    idcliente integer,
    idusuario integer,
    datapedido timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    valortotal numeric(10, 2),
    CONSTRAINT pedido_pkey PRIMARY KEY (idpedido)
);

CREATE TABLE IF NOT EXISTS public.cliente
(
    idcliente serial NOT NULL,
    idusuario integer,
    datacadastrocliente timestamp without time zone DEFAULT now(),
    CONSTRAINT cliente_pkey PRIMARY KEY (idcliente)
);

CREATE TABLE IF NOT EXISTS public.usuario
(
    idusuario serial NOT NULL,
    nomeusuario character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    senha character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT usuario_pkey PRIMARY KEY (idusuario),
    CONSTRAINT usuario_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.funcionario
(
    idfuncionario serial NOT NULL,
    nomefuncionario character varying(100) COLLATE pg_catalog."default" NOT NULL,
    idcargo integer,
    idusuario integer,
    CONSTRAINT funcionario_pkey PRIMARY KEY (idfuncionario),
    CONSTRAINT funcionario_idusuario_key UNIQUE (idusuario)
);

CREATE TABLE IF NOT EXISTS public.cargos
(
    idcargo serial NOT NULL,
    nomecargo character varying(100) COLLATE pg_catalog."default" NOT NULL,
    codigocargo character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT cargos_pkey PRIMARY KEY (idcargo),
    CONSTRAINT cargos_codigocargo_key UNIQUE (codigocargo)
);

CREATE TABLE IF NOT EXISTS public.pagamento
(
    idpedido integer NOT NULL,
    datapagamento timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    valorpago numeric(10, 2),
    idformapagamento integer,
    CONSTRAINT pagamento_pkey PRIMARY KEY (idpedido)
);

CREATE TABLE IF NOT EXISTS public.formadepagamento
(
    idformapagamento serial NOT NULL,
    nomeformapagamento character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT formadepagamento_pkey PRIMARY KEY (idformapagamento)
);

CREATE TABLE IF NOT EXISTS public.pagamento_has_formadepagamento
(
    idpedido integer NOT NULL,
    idformapagamento integer NOT NULL,
    valorpago numeric(10, 2) NOT NULL,
    CONSTRAINT pagamento_has_formadepagamento_pkey PRIMARY KEY (idpedido, idformapagamento)
);

ALTER TABLE IF EXISTS public.produto
    ADD CONSTRAINT produto_idcategoria_fkey FOREIGN KEY (idcategoria)
    REFERENCES public.categoria (idcategoria) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.pedidoproduto
    ADD CONSTRAINT pedidoproduto_idpedido_fkey FOREIGN KEY (idpedido)
    REFERENCES public.pedido (idpedido) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.pedidoproduto
    ADD CONSTRAINT pedidoproduto_idproduto_fkey FOREIGN KEY (idproduto)
    REFERENCES public.produto (idproduto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.pedido
    ADD CONSTRAINT pedido_idcliente_fkey FOREIGN KEY (idcliente)
    REFERENCES public.cliente (idcliente) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.pedido
    ADD CONSTRAINT pedido_idusuario_fkey FOREIGN KEY (idusuario)
    REFERENCES public.usuario (idusuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.cliente
    ADD CONSTRAINT fk_cliente_usuario FOREIGN KEY (idusuario)
    REFERENCES public.usuario (idusuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.funcionario
    ADD CONSTRAINT funcionario_idcargo_fkey FOREIGN KEY (idcargo)
    REFERENCES public.cargos (idcargo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.funcionario
    ADD CONSTRAINT funcionario_idusuario_fkey FOREIGN KEY (idusuario)
    REFERENCES public.usuario (idusuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS funcionario_idusuario_key
    ON public.funcionario(idusuario);


ALTER TABLE IF EXISTS public.pagamento
    ADD CONSTRAINT pagamento_idformapagamento_fkey FOREIGN KEY (idformapagamento)
    REFERENCES public.formadepagamento (idformapagamento) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pagamento
    ADD CONSTRAINT pagamento_idpedido_fkey FOREIGN KEY (idpedido)
    REFERENCES public.pedido (idpedido) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS pagamento_pkey
    ON public.pagamento(idpedido);


ALTER TABLE IF EXISTS public.pagamento_has_formadepagamento
    ADD CONSTRAINT pagamento_has_formadepagamento_idformapagamento_fkey FOREIGN KEY (idformapagamento)
    REFERENCES public.formadepagamento (idformapagamento) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.pagamento_has_formadepagamento
    ADD CONSTRAINT pagamento_has_formadepagamento_idpedido_fkey FOREIGN KEY (idpedido)
    REFERENCES public.pagamento (idpedido) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;

END;